services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  
    environment:
      - DB_HOST=db
      - DB_USER=POSTGRES
      - DB_PASSWORD=Admin123
      - DB_NAME=laligadb
    restart: unless-stopped
    healthcheck:  
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=POSTGRES
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=laligadb
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U POSTGRES -d laligadb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data: